---
application:
  name: "koempro-server"
  project: "Koempro Api"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "freedbtech_Koempro"
  version: "8"
routers:
- name: "main-koempro-server"
  routes:
  - application_name: "koempro-server"
    paths:
    - "/*"
